### ISSUE TITLE
When a TA logs out, they get demoted to a student

### ISSUE THREAD

**Issue by dlike230** [KeenWill/OHQueue#30]

**Comment by KeenWill** [comment]
I believe this is because when they log back in, our login routine resets the isTA field to false

**Comment by KeenWill** [comment]
Perhaps this line is malfunctioning?

[https://github.com/KeenWill/OHQueue/blob/ac62ae9ad7dbe05c3c8aca0d188712851a56591e/src/app/%40core/auth/auth.service.ts#L161](url)
